### PR TITLE
using  BT  instead of HS in index_table.hpp

### PR DESCRIPTION
**Pull request by JacksonYao287**
homeobject has some error when compiling with the current version of homestore. this PR is to resolve this issue

### CODE REVIEW

File: src/include/homestore/btree/detail/simple_node.hpp [hunk 1]
```diff
@@ -225,63 +225,67 @@ class SimpleNode : public VariantNode< K, V > {
...
-                } else {
-                    fmt::format_to(std::back_inserter(str), "]{}{}- [{}", delimiter, i, cur_key);
+            if (this->total_entries() == 0) {
+                fmt::format_to(std::back_inserter(str), " [EMPTY] ");
+                return str;
+            }
+            if (!this->is_leaf()) {
+                fmt::format_to(std::back_inserter(str), " [");
+                for (uint32_t i{0}; i < this->total_entries(); ++i) {
+                    uint32_t cur_key = BtreeNode::get_nth_key< K >(i, false).key();
```
Comment (xiaoxichen) [inline src/include/homestore/btree/detail/simple_node.hpp:248]:
```
/var/home/centos/.conan/data/homestore/6.4.13-78/oss/master/package/3db5c19199a28dd539c597582be6f6a2e43d437a/include/homestore/btree/detail/simple_node.hpp: In instantiation of ‘std::string homestore::SimpleNode<K, V>::to_string_keys(bool) const [with K = homeobject::BlobRouteKey; V = homeobject::BlobRouteValue; std::string = std::__cxx11::basic_string<char>]’:
/var/home/centos/.conan/data/homestore/6.4.13-78/oss/master/package/3db5c19199a28dd539c597582be6f6a2e43d437a/include/homestore/btree/detail/simple_node.hpp:227:17:   required from here
/var/home/centos/.conan/data/homestore/6.4.13-78/oss/master/package/3db5c19199a28dd539c597582be6f6a2e43d437a/include/homestore/btree/detail/simple_node.hpp:245:77: error: cannot convert ‘homeobject::BlobRoute’ to ‘uint32_t’ {aka ‘unsigned int’} in initialization
  245 |                 uint32_t cur_key = BtreeNode::get_nth_key< K >(i, false).key();
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                             |
      |                                                                             homeobject::BlobRoute
/var/home/centos/.conan/data/homestore/6.4.13-78/oss/master/package/3db5c19199a28dd539c597582be6f6a2e43d437a/include/homestore/btree/detail/simple_node.hpp:254:70: error: cannot convert ‘homeobject::BlobRoute’ to ‘uint32_t’ {aka ‘unsigned int’} in initialization
  254 |         uint32_t prev_key = BtreeNode::get_nth_key< K >(0, false).key();
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                      |
      |                                                                      homeobject::BlobRoute
/var/home/centos/.conan/data/homestore/6.4.13-78/oss/master/package/3db5c19199a28dd539c597582be6f6a2e43d437a/include/homestore/btree/detail/simple_node.hpp:256:94: error: cannot convert ‘homeobject::BlobRoute’ to ‘uint32_t’ {aka ‘unsigned int’} in initialization
  256 |         uint32_t last_key = BtreeNode::get_nth_key< K >(this->total_entries() - 1, false).key();
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                                              |
      |                                                                                              homeobject::BlobRoute
/var/home/centos/.conan/data/homestore/6.4.13-78/oss/master/package/3db5c19199a28dd539c597582be6f6a2e43d437a/include/homestore/btree/detail/simple_node.hpp:267:64: error: cannot convert ‘homeobject::BlobRoute’ to ‘uint32_t’ {aka ‘unsigned int’} in assignment
  267 |             cur_key = BtreeNode::get_nth_key< K >(i, false).key();
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                |
      |                                                                homeobject::BlobRoute

```

Comment (xiaoxichen) [reply src/include/homestore/btree/detail/simple_node.hpp:248]: @hkadayam  this introduced by the https://github.com/eBay/HomeStore/pull/437/

File: src/include/homestore/btree/detail/simple_node.hpp [hunk 2]
```diff
@@ -225,63 +225,67 @@ class SimpleNode : public VariantNode< K, V > {
     }
 
     std::string to_string_keys(bool print_friendly = false) const override {
-        std::string delimiter = print_friendly ? "\n" : "\t";
```
Comment (hkadayam) [inline src/include/homestore/btree/detail/simple_node.hpp:228]: You can remove this function altogether, it was not correct code and it was merged here by mistake.

Comment (JacksonYao287) [reply src/include/homestore/btree/detail/simple_node.hpp:228]: this part is now wrapped by  `#if 0 and #endif`, it can be removed when revisiting here and implement this function

**Review by xiaoxichen — APPROVED** [review]

**Comment by xiaoxichen** [comment]
@JacksonYao287 you can remove the to_string_key() or leave it commented out,  both fine

File: src/include/homestore/btree/detail/simple_node.hpp (hunk 2 above)
Comment (shosseinimotlagh) [reply src/include/homestore/btree/detail/simple_node.hpp:228]: @JacksonYao287 Please wrap it with #if 0 because it is still beneficial in some cases. Do it for all to_string_keys()

Comment (JacksonYao287) [reply src/include/homestore/btree/detail/simple_node.hpp:228]: sure
@shosseinimotlagh

**Review by shosseinimotlagh — DISMISSED** [review]

**Review by xiaoxichen — APPROVED** [review]
LGTM.  Pls merge it after testing on real drive.

File: src/lib/device/device_manager.cpp [hunk 3]
```diff
@@ -321,8 +323,8 @@ shared< VirtualDev > DeviceManager::create_vdev(vdev_parameters&& vparam) {
         auto total_chunk_num_in_pdev =
             static_cast< uint32_t >(vparam.num_chunks * (pdev->data_size() / static_cast< float >(total_type_size)));
 
-        LOGINFO("{} chunks is created on pdev {} for vdev {}", total_chunk_num_in_pdev, pdev->get_devname(),
-                vparam.vdev_name)
+        LOGINFO("{} chunks is created on pdev {} for vdev {}, pdev data size is {}", total_chunk_num_in_pdev,
```
Comment (xiaoxichen) [inline src/lib/device/device_manager.cpp:326]: can we add an assert to ensure `total_chunk_num_in_pdev <= vparam.num_chunks`

Comment (JacksonYao287) [reply src/lib/device/device_manager.cpp:326]: sure

**Review by xiaoxichen — APPROVED** [review]
